### ISSUE TITLE
Permission denied (publickey) on mysocketctl connect

### ISSUE THREAD

**Issue by mboscovich** [mysocketio/mysocketctl#13]
When i try to connect a socket, i get a publickey error. I think its related to ssh login process.

```
mboscovich@tesla03:~ $ mysocketctl login --email "mboscovich@gmail.com" --password "XXXXXXXXXXXXX"
Logged in! Token stored in /home/mboscovich/.mysocketio_token

mboscovich@tesla03:~ $ mysocketctl connect --port 8080 --name "prueba"
+--------------------------------------+--------------------------------------+---------+------+--------+
|              socket_id               |               dns_name               | port(s) | type |  name  |
+--------------------------------------+--------------------------------------+---------+------+--------+
| a79e3ce9-27f0-4abc-97bd-9991bbb3e5a7 | delicate-brook-3736.edge.mysocket.io |  80 443 | http | prueba |
+--------------------------------------+--------------------------------------+---------+------+--------+

Connecting to Server: ssh.mysocket.io

6fc0e0e8fb5c498cbb5d783ded660ac0@ssh.mysocket.io: Permission denied (publickey).
Disconnected... Automatically reconnecting now..
Press ctrl-c to exit
6fc0e0e8fb5c498cbb5d783ded660ac0@ssh.mysocket.io: Permission denied (publickey).
Disconnected... Automatically reconnecting now..
Press ctrl-c to exit
6fc0e0e8fb5c498cbb5d783ded660ac0@ssh.mysocket.io: Permission denied (publickey).
Disconnected... Automatically reconnecting now..
Press ctrl-c to exit
6fc0e0e8fb5c498cbb5d783ded660ac0@ssh.mysocket.io: Permission denied (publickey).
Disconnected... Automatically reconnecting now..
Press ctrl-c to exit
```

I think the problem could be, that pub key isn't on the remote host. This is the ssh output

```
mboscovich@tesla03:~ $ ssh c43803bf25064017a3948ebc06fd3f65@ssh.mysocket.io -i ~/.ssh/id_rsa  -v
OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020
debug1: Reading configuration data /home/mboscovich/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Connecting to ssh.mysocket.io [99.83.233.138] port 22.
debug1: Connection established.
debug1: identity file /home/mboscovich/.ssh/id_rsa type 0
debug1: identity file /home/mboscovich/.ssh/id_rsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.2p1 Ubuntu-4ubuntu0.1
debug1: match: OpenSSH_8.2p1 Ubuntu-4ubuntu0.1 pat OpenSSH* compat 0x04000000
debug1: Authenticating to ssh.mysocket.io:22 as 'c43803bf25064017a3948ebc06fd3f65'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:35ZtwZ4HRme2W3Mktt/ZQEM8NlgvPOG3Q6w26NrxHA4
debug1: Host 'ssh.mysocket.io' is known and matches the ECDSA host key.
debug1: Found key in /home/mboscovich/.ssh/known_hosts:264
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: /home/mboscovich/.ssh/id_rsa RSA SHA256:2biByZSAZxvtsZDbxPwTIMqlXJmTPdM1h+BtQloHX2g explicit agent
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: /home/mboscovich/.ssh/id_rsa RSA SHA256:2biByZSAZxvtsZDbxPwTIMqlXJmTPdM1h+BtQloHX2g explicit agent
debug1: Authentications that can continue: publickey
debug1: No more authentication methods to try.
c43803bf25064017a3948ebc06fd3f65@ssh.mysocket.io: Permission denied (publickey).
```

**Comment by atoonk** [comment]
hi Maximiliano,

sorry about that. there was a temporary hick-up with distributing the config in the last 3 hours.
this has now been resolved. Can you try it again?

thanks
 Andree

**Comment by mboscovich** [comment]
Hi Andree, 
Yes!, thats right, the problem is fixed!.
Thank you for the instant reply and fix.
Great service!

**Comment by gklasen** [comment]
Hey, @atoonk, seems like this issue is back. I was running into it, without changes on my so far working config?

**Comment by atoonk** [comment]
Hi @gklasen 
i will need some more info, like what socket_id. Do you see the problem right now?
i just tested myself to the EU and US-west server and it seems to work ok now.

did you use the regular client? if so what version?

**Comment by gklasen** [comment]
Version: mysocketctl 0.14

Socket_ID: Cannot be measured, system is cleaning up after i abort the command.

Error is:

```
Logged in! Token stored in /root/.mysocketio_token

Traceback (most recent call last):
  File "/usr/local/bin/mysocketctl", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mysocketctl/connect.py", line 100, in connect
    print_sockets([new_conn])
  File "/usr/local/lib/python3.7/dist-packages/mysocketctl/utils.py", line 153, in print_sockets
    socket["cloud_authentication"],
KeyError: 'cloud_authentication'
```

Even registered a new account, but can not login into that as well.

**Comment by atoonk** [comment]
hi @gklasen 
this was a bug in v0.13 I believe. v0.14 should have solved this. Are you sure you're running v0.14?
line 153 of utils.py in v0.14 is ```  socket["cloud_authentication_enabled"], ```
https://github.com/mysocketio/mysocketctl/blob/main/mysocketctl/utils.py#L153

can you make sure you run v.014

check version:
```
pip3 freeze | grep mysocketctl
mysocketctl==0.14
```

check line 153 of utils.py
```
sed -n 153p /usr/local/lib/python3.7/dist-packages/mysocketctl/utils.py
            socket["cloud_authentication_enabled"],
```

**Comment by gklasen** [comment]
I get the output as expected.  Sorry, i was testing different versions and left with 10.13. Back to 10.14, i got the output expected, but still the error from @mboscovich. 

But: Since ~10 minutes, it is working again like it should. So issue for now is solved, but not with the hick-ups in general, it seems.

**Comment by atoonk** [comment]
That's good to hear @gklasen 
I'm committed to getting to the bottom of what you're seeing. in order to do so, I need to reproduce it. can you tell me exactly what you're doing? Something I can easily reproduce / try myself?

**Comment by gklasen** [comment]
Actually, all i am doing was creating an account

`mysocketctl connect --port 8443 --name "COMPRISE Personal Server" --type https`,

logging in 

`mysocketctl login --email "comprise_dev@web.de" --password *********`

and running: 

`mysocketctl connect --port 8443 --name "COMPRISE Personal Server" --type https`

So kind of reproducable for every kind of account. I was not changing anything, just deleted old sockets here and there, and connected again.

**Comment by atoonk** [comment]
what is the exact error you get when you do this? 

this, or something else?
```
***@ssh.mysocket.io: Permission denied (publickey).
Disconnected... Automatically reconnecting now..
```

**Comment by gklasen** [comment]
Got the error you pasted, except that ...

> Disconnected... Automatically reconnecting now..

... was missing. Only got 

> ***@ssh.mysocket.io: Permission denied (publickey).

**Comment by atoonk** [comment]
hhm. I will need some more details..

1) can you paste the complete output of a failed attempt.

2) are you using docker? if so what base docker container? (I may be able to use that to reproduce)

3) does the system have ssh installed? (what is the output of ```which ssh``` (if not it will fall back to paramiko. )

4) if not, can you install the ssh client and see if it makes a difference

5) in addition to step1, can you do the same with debug enabled, like 
```MYSOCKET_DEBUG=TRUE mysocketctl connect --port 8443 --name "COMPRISE Personal Server" --type https```

6) are you sure the machine has access to the private key? what is the location of the private key? can you show the output of ```ls -la <your private key> ```(I'm interested in the key type / name) ***don't*** paste the content of your private key

**Comment by atoonk** [comment]
@gklasen I'm happy to jump on a call if that works better for you. we can try and troubleshoot it together. just let me know. you can email me at andree at mysocket

**Comment by atoonk** [comment]
any changes @gklasen ? let me know if we need to keep digging or can close this

**Comment by gklasen** [comment]
Hey, sorry. 

It is working again, so it seems like it was a temporary issue. Feel free to close.
